dataset:
  tar_path: /data/Database/SPGC/tarFiles_copy/
  untar_path: /data/Database/SPGC/baseline_data/
  metadata_path: /data/Database/SPGC/baseline_data/metadata/
  langs: ['Marathi', 'Telugu', 'Hindi']
  forced_algined_path: /data/Sathvik/DeepForcedAligner_LIMMITS32_data/ #https://github.com/bloodraven66/DeepForcedAligner
  duration_path_postfix: _data_outputs/durations
  mel_path_postfix: _data/mels
  token_postfix: _data/tokens/
  symbols_file: data/symbols.pkl
  speakers: ['M', 'F']
  force_untar: false
  force_getdur: false
  force_genfilelist: false
  stop_prep: false
  num_proc: 48 # extract wav durations
  limit_total_dur: 5 #for track 1 and 3
  first_dataloader_dur: 3 #for track 1 and 3
  dev_dur: 0.7 #for track 1 and 3
  test_dur: 0.2 #for track 1 and 3
  

signal:
  sampling_rate: 22050  
  filter_length: 1024
  hop_length: 256
  win_length: 1024
  n_mels: 80
  mel_fmin: 0.0
  mel_fmax: 8000.0
  power: 1

track: track1

model:
  name: ml_fastspeech
  model_config: hparams/track1_model.yaml
  save_every: 100
  lr: 0.0001
  weight_decay: 1e-6
  num_epochs: 501
  loader1_epochs: 50
  batch_size: 24
  chk_path: 'saved_models'
  chk_tag: ''
  infer: false
  load_chk: false
  device: cuda:1
  gen_sample_loc: "samples"
  
wandb_logging: 
  disable: false
  wandb_project: icassp_limmits23
  share_freq: 25
  num_samples: 1



  



